name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"
    branches:
      - MOBILE-1320

jobs:
#  analyze:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: actions/setup-java@v1
#        with:
#          java-version: "12.x"
#      - uses: subosito/flutter-action@v1
#        with:
#          channel: "stable"
#      - name: Run CI
#        run: bash ./scripts/run_ci_tasks.sh -z
#  android:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: actions/setup-java@v1
#        with:
#          java-version: "12.x"
#      - uses: subosito/flutter-action@v1
#        with:
#          channel: "stable"
#      - name: Run CI
#        run: bash ./scripts/run_ci_tasks.sh -a
#  ios:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: actions/setup-java@v1
#        with:
#          java-version: "12.x"
#      - uses: subosito/flutter-action@v1
#        with:
#          channel: "stable"
#      - name: Run CI
#        run: bash ./scripts/run_ci_tasks.sh -i
  upload-docs:
    runs-on: ubuntu-latest
#    needs: [analyze, android, ios]
    steps:
      - uses: actions/checkout@v1
      - name: Install dart
        run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https
          sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
          sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
          sudo apt-get update
          sudo apt-get install dart
          export PATH="$PATH:/usr/lib/dart/bin"
      - name: Generate documentation
        run: |
          dartdoc
      - name: Download docs tar
        uses: actions/download-artifact@v1
        with:
          name: docs
          path: ./doc/api/
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "270.0.0"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
#      - name: Slack Notification
#        uses: homoluctus/slatify@master
#        if: always()
#        with:
#          type: ${{ job.status }}
#          job_name: "Uploaded flutter API docs"
#          url: ${{ secrets.MOBILE_SLACK_WEBHOOK }}
#  publish:
#    runs-on: ubuntu-latest
#    needs: [analyze, android, ios]
#    steps:
#      - uses: actions/checkout@v1
#      - name: Publish Dart/Flutter package
#        uses: sakebook/actions-flutter-pub-publisher@v1.2.1
#        with:
#          # Google Account credential JSON
#          credential:  ${{ secrets.PUB_DEV_CREDENTIALS }}
#  finished:
#    runs-on: ubuntu-latest
#    needs: [analyze, android, ios, publish]
#    steps:
#      - name: Slack Notification
#        uses: homoluctus/slatify@master
#        if: always()
#        with:
#          type: ${{ job.status }}
#          job_name: ":raised_hands: Airship Flutter Plugin Released! :raised_hands:"
#          url: ${{ secrets.MOBILE_SLACK_WEBHOOK }}
